// Package ide contains the IDE configuration generators for C++ projects.
//
// Each supported IDE has its own implementation file:
//   - vscode.go  — Visual Studio Code (.vscode/)
//   - clion.go   — CLion (additional settings for CMakePresets.json)
//   - nvim.go    — Neovim (.nvim.lua)
//
// All generation functions receive a *Data with the necessary information
// and the root path of the project where the files will be created.
package ide

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// ─────────────────────────────────────────────────────────────────────────────
// Data — shared data structure among all IDE generators
// ─────────────────────────────────────────────────────────────────────────────

// Data contains the necessary information to generate the configurations
// for any IDE supported by cpp-gen.
//
// It is a subset of generator.TemplateData, exposed as its own type
// to avoid circular dependency between the generator and ide packages.
type Data struct {
	// ProjectName is the original project name (e.g.: "meu-projeto").
	// Used in labels, task titles and executable names.
	ProjectName string

	// NameUpper is the name in UPPER_SNAKE_CASE (e.g.: "MEU_PROJETO").
	// Used in environment variables and CMake defines.
	NameUpper string

	// IsExecutable indicates whether the project generates an executable binary.
	// When true, launch/debug configurations point to the binary.
	IsExecutable bool

	// UseVCPKG indicates whether the project uses VCPKG as the package manager.
	// When true, debug/build presets use the vcpkg-* presets.
	UseVCPKG bool

	// DebugAdapter is the chosen debugger backend: "lldb", "gdb", or "both".
	// Used by IDE generators to emit the appropriate debug configurations.
	DebugAdapter string
}

// ─────────────────────────────────────────────────────────────────────────────
// CMake preset selectors
// ─────────────────────────────────────────────────────────────────────────────

// ConfigurePreset returns the CMake configure preset name to be used
// as default in the IDE build configurations.
//
// If VCPKG is enabled, returns the "vcpkg-debug" preset.
// Otherwise, returns "debug".
func (d *Data) ConfigurePreset() string {
	if d.UseVCPKG {
		return "vcpkg-debug"
	}
	return "debug"
}

// BuildPreset returns the CMake build preset name to be used
// in the IDE build tasks.
func (d *Data) BuildPreset() string {
	if d.UseVCPKG {
		return "build-vcpkg-debug"
	}
	return "build-debug"
}

// TestPreset returns the CMake test preset name to be used
// in the IDE test tasks.
func (d *Data) TestPreset() string {
	if d.UseVCPKG {
		return "test-vcpkg-debug"
	}
	return "test-debug"
}

// BinaryPath returns the relative path to the executable generated by the build,
// based on the active debug preset.
//
// Used in launch/debug configurations to point to the correct binary.
// The binary is placed in build/<preset>/bin/<name> as defined in CMakeLists.txt.
func (d *Data) BinaryPath() string {
	preset := d.ConfigurePreset()
	return fmt.Sprintf("${workspaceFolder}/build/%s/bin/%s", preset, d.ProjectName)
}

// UseLLDB returns true if LLDB debug configurations should be generated.
// True when DebugAdapter is "lldb" or "both".
func (d *Data) UseLLDB() bool {
	return d.DebugAdapter == "lldb" || d.DebugAdapter == "both"
}

// UseGDB returns true if GDB debug configurations should be generated.
// True when DebugAdapter is "gdb" or "both".
func (d *Data) UseGDB() bool {
	return d.DebugAdapter == "gdb" || d.DebugAdapter == "both"
}

// ─────────────────────────────────────────────────────────────────────────────
// High-level generation functions
// ─────────────────────────────────────────────────────────────────────────────

// GenerateVSCode generates the Visual Studio Code configurations for the project.
// Creates the .vscode/ directory with the files:
//   - tasks.json       — build, clean and test tasks
//   - launch.json      — debug configurations (lldb and cppdbg)
//   - settings.json    — workspace configurations (clangd, cmake tools)
//   - extensions.json  — recommended extensions for the project
func GenerateVSCode(root string, data *Data, verbose bool) error {
	return generateVSCode(root, data, verbose)
}

// GenerateCLion generates additional configurations for CLion.
// CLion natively reads CMakePresets.json (already generated by cmake.go),
// therefore this generator creates only a .idea/externalTools.xml file
// with additional tool integrations.
func GenerateCLion(root string, data *Data, verbose bool) error {
	return generateCLion(root, data, verbose)
}

// GenerateNvim generates project configurations for Neovim.
// Creates a .nvim.lua file at the project root with configurations
// for LSP, project keymaps and DAP integration for debugging.
func GenerateNvim(root string, data *Data, verbose bool) error {
	return generateNvim(root, data, verbose)
}

// GenerateZed generates the Zed editor configurations for the project.
// Creates the .zed/ directory with the files:
//   - settings.json  — workspace configurations (clangd LSP, clang-format,
//     editor, inlay hints and debug adapter)
//   - tasks.json     — configure, build, clean, test and run tasks
func GenerateZed(root string, data *Data, verbose bool) error {
	return generateZed(root, data, verbose)
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal utilities shared among IDE generators
// ─────────────────────────────────────────────────────────────────────────────

// writeIDEFile creates (or overwrites) a file at the specified path.
// Creates all necessary parent directories with 0755 permission.
// If verbose is true, prints the path of the created file.
func writeIDEFile(path, content string, verbose bool) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("criar diretório %q: %w", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("escrever arquivo %q: %w", path, err)
	}

	if verbose {
		fmt.Printf("    + %s\n", path)
	}

	return nil
}

// renderIDETemplate processes a Go template (text/template) with the provided
// data and returns the result as a string.
func renderIDETemplate(name, tmpl string, data any) (string, error) {
	t, err := template.New(name).Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("parse do template %q: %w", name, err)
	}

	var sb strings.Builder
	if err := t.Execute(&sb, data); err != nil {
		return "", fmt.Errorf("execução do template %q: %w", name, err)
	}

	return sb.String(), nil
}

// writeIDETemplate combines renderIDETemplate and writeIDEFile:
// processes the template and writes the result to the specified file.
func writeIDETemplate(path, name, tmpl string, data any, verbose bool) error {
	content, err := renderIDETemplate(name, tmpl, data)
	if err != nil {
		return err
	}
	return writeIDEFile(path, content, verbose)
}
