// Package ide contains the IDE configuration generators for C++ projects.
package ide

import (
	"fmt"
	"path/filepath"
)

// ─────────────────────────────────────────────────────────────────────────────
// generateZed — entry point
// ─────────────────────────────────────────────────────────────────────────────

// generateZed creates the .zed/ directory with complete configurations for the
// Zed editor (https://zed.dev), a modern, high-performance editor
// written in Rust.
//
// Generated files:
//
//   - .zed/settings.json  — workspace configurations: clangd LSP,
//     clang-format, editor preferences, inlay hints and DAP (debug)
//   - .zed/tasks.json     — cmake configure, build, clean, test
//     and binary execution tasks, accessible via Zed's task runner
//
// Compatibility: Zed 0.140+ (stable C++ LSP and tasks support).
// Reference: https://zed.dev/docs/configuring-zed
func generateZed(root string, data *Data, verbose bool) error {
	zedDir := filepath.Join(root, ".zed")

	files := []struct {
		name     string
		relPath  string
		tmplName string
		tmpl     string
	}{
		{
			name:     "settings.json",                        // file name (for error messages)
			relPath:  filepath.Join(zedDir, "settings.json"), // path relative to root
			tmplName: "zed_settings",                         // Go template name
			tmpl:     tmplZedSettings,                        // template content
		},
		{
			name:     "tasks.json",
			relPath:  filepath.Join(zedDir, "tasks.json"),
			tmplName: "zed_tasks",
			tmpl:     tmplZedTasks,
		},
	}

	for _, f := range files {
		if err := writeIDETemplate(f.relPath, f.tmplName, f.tmpl, data, verbose); err != nil {
			return fmt.Errorf("gerar .zed/%s: %w", f.name, err)
		}
	}

	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Template: .zed/settings.json
// ─────────────────────────────────────────────────────────────────────────────

// tmplZedSettings is the template for .zed/settings.json.
//
// The Zed settings.json file defines workspace configurations that
// override the user's global settings (~/.config/zed/settings.json)
// only for this project. This ensures that all collaborators use
// the same formatting, LSP and editor configurations.
//
// Configured sections:
//
//	C and C++ languages:
//	  - Automatic formatting on save via clang-format
//	  - Tab size of 4 spaces, no tabs
//	  - Inlay hints (variable types, parameter names)
//
//	LSP — Clangd:
//	  - compile-commands-dir pointing to the debug preset
//	  - integrated clang-tidy
//	  - header-insertion via IWYU
//	  - completion all-scopes
//
//	General editor:
//	  - Exclusion of build directories from searches and file tree
//	  - Unix line endings (LF)
//	  - Trim whitespace on save
//
//	DAP — Debug Adapter Protocol:
//	  - Debug configurations for LLDB (Linux/macOS) and CodeLLDB
//	  - Point to the binary generated by the debug preset
//
// Reference: https://zed.dev/docs/configuring-zed
//
//	https://zed.dev/docs/languages/c
const tmplZedSettings = `{
  // ============================================================================
  // .zed/settings.json — Configurações de workspace para {{ .ProjectName }}
  // ============================================================================
  // Estas configurações aplicam-se APENAS a este workspace e sobrepõem
  // as configurações globais do usuário em ~/.config/zed/settings.json.
  //
  // Documentação: https://zed.dev/docs/configuring-zed
  // ============================================================================

  // ── Configurações de linguagem ────────────────────────────────────────────

  "languages": {

    // ── C++ ───────────────────────────────────────────────────────────────────
    "C++": {
      // Tamanho de indentação (consistente com .clang-format)
      "tab_size": 4,

      // Usa espaços em vez de tabs
      "hard_tabs": false,

      // Comprimento máximo de linha para guia visual (consistente com .clang-format)
      "preferred_line_length": 100,

      // Formata o arquivo ao salvar usando o clang-format instalado no sistema.
      // O Zed usa o .clang-format da raiz do projeto automaticamente.
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "clang-format",
          // Lê o arquivo da stdin e escreve na stdout (-style=file usa .clang-format)
          "arguments": ["--style=file", "-"]
        }
      },

      // Inlay hints: exibe tipos de variáveis 'auto' e nomes de parâmetros inline.
      // Requer suporte do servidor Clangd (habilitado na seção "lsp" abaixo).
      "inlay_hints": {
        "enabled": true,
        "show_parameter_hints": true,
        "show_type_hints": true,
        "show_other_hints": true
      },

      // Fim de linha Unix (LF) — evita problemas de diff em ambientes mistos
      "line_ending": "unix"
    },

    // ── C (compartilha as mesmas configurações do C++) ─────────────────────
    "C": {
      "tab_size": 4,
      "hard_tabs": false,
      "preferred_line_length": 100,
      "format_on_save": "on",
      "formatter": {
        "external": {
          "command": "clang-format",
          "arguments": ["--style=file", "-"]
        }
      },
      "inlay_hints": {
        "enabled": true,
        "show_parameter_hints": true,
        "show_type_hints": true,
        "show_other_hints": true
      },
      "line_ending": "unix"
    }
  },

  // ── LSP — Clangd ──────────────────────────────────────────────────────────
  //
  // Configura o servidor de linguagem Clangd para este projeto.
  // O Zed usa o Clangd como LSP padrão para C/C++ e o gerencia automaticamente.
  //
  // O Clangd encontra o compile_commands.json gerado pelo CMake no diretório
  // especificado em "compile-commands-dir". O preset de debug é usado como
  // padrão pois é o ambiente de desenvolvimento mais comum.
  //
  // Referência: https://clangd.llvm.org/config.html

  "lsp": {
    "clangd": {
      "binary": {
        // Caminho para o binário clangd. "clangd" usa o do PATH.
        // Descomente e ajuste se precisar de uma versão específica:
        // "path": "/usr/bin/clangd-18",
        "path": "clangd",

        // Argumentos passados ao servidor Clangd ao iniciar.
        "arguments": [
          // Aponta para o compile_commands.json do preset de debug.
          // Gerado automaticamente pelo CMake (CMAKE_EXPORT_COMPILE_COMMANDS=ON).
          "--compile-commands-dir=build/{{if .UseVCPKG}}vcpkg-debug{{else}}debug{{end}}",

          // Número de threads para indexação em background.
          // Ajuste conforme o número de cores disponíveis.
          "--j=4",

          // Inclui símbolos de todos os escopos no autocompletar,
          // não apenas do escopo atual.
          "--all-scopes-completion=true",

          // Sugere incluir headers automaticamente ao completar
          // símbolos desconhecidos (usa IWYU — Include What You Use).
          "--header-insertion=iwyu",

          // Habilita diagnósticos do clang-tidy inline no editor.
          // As regras são configuradas no .clangd da raiz do projeto.
          "--clang-tidy",

          // Habilita inlay hints no protocolo LSP.
          "--inlay-hints",

          // Habilita leitura do arquivo .clangd do projeto.
          "--enable-config",

          // Nível de log do servidor (error | warning | info | verbose).
          "--log=error",

          // Habilita cache em disco para acelerar reinicializações.
          "--pch-storage=memory"
        ]
      },

      // Configurações de inicialização do Clangd (initializationOptions).
      "initialization_options": {
        // Habilita o índice em background de todo o projeto.
        "index": {
          "enableBackgroundIndexing": true
        },
        // Exibe a documentação em hover no formato Markdown.
        "hover": {
          "showAKA": true
        }
      }
    }
  },

  // ── Editor ────────────────────────────────────────────────────────────────

  // Remove espaços em branco no final das linhas ao salvar.
  "remove_trailing_whitespace_on_save": true,

  // Insere uma linha em branco no final de cada arquivo ao salvar.
  "ensure_final_newline_on_save": true,

  // Exibe a régua vertical na coluna 100 (consistente com .clang-format).
  "rulers": [100],

  // Exibe números de linha relativos (útil para navegação com hjkl/Vim mode).
  // Altere para "absolute" se preferir números absolutos.
  "relative_line_numbers": false,

  // Comportamento do git blame inline.
  "git": {
    "inline_blame": {
      "enabled": true,
      // Exibe o blame apenas após o cursor ficar parado por 600ms.
      "delay_ms": 600
    }
  },

  // ── Arquivo — Exclusões ───────────────────────────────────────────────────
  //
  // Oculta diretórios gerados da árvore de arquivos do Zed e das buscas.
  // NOTA: isto não afeta o .gitignore — apenas a visualização no editor.

  "file_scan_exclusions": [
    "**/.git",
    "**/build",
    "**/build-*",
    "**/install",
    "**/dist",
    "**/vcpkg_installed",
    "**/.cache",
    "**/*.o",
    "**/*.a",
    "**/*.so",
    "**/*.dylib",
    "**/*.d"
  ],

  // ── Terminal integrado ────────────────────────────────────────────────────

  "terminal": {
    // Diretório de trabalho padrão do terminal integrado.
    // "current_project_directory" abre sempre na raiz do workspace.
    "working_directory": "current_project_directory",

    // Shell padrão (null = usa o shell do sistema definido em $SHELL).
    "shell": { "with_arguments": { "program": "bash", "args": [] } }
  },

  // ── DAP — Debug Adapter Protocol ─────────────────────────────────────────
  //
  // Configurações de debug integrado do Zed via DAP.
  // Requer o adaptador de debug instalado:
  //   - LLDB: instalado junto com o Xcode CLT (macOS) ou lldb (Linux)
  //   - CodeLLDB: extensão autônoma (https://github.com/vadimcn/codelldb)
  //
  // Para iniciar o debug: Ctrl+Shift+D (ou pelo menu Run > Debug)
  //
  // Referência: https://zed.dev/docs/debugger

  "debugger": {
    // Adapters disponíveis para C++.
    // O Zed detecta automaticamente o adapter disponível no sistema.
    "adapters": {
      // LLDB nativo (macOS/Linux com clang)
      "lldb": {
        "type": "lldb"
      }
    }
  }
}
`

// ─────────────────────────────────────────────────────────────────────────────
// Template: .zed/tasks.json
// ─────────────────────────────────────────────────────────────────────────────

// tmplZedTasks is the template for .zed/tasks.json.
//
// Defines the build tasks accessible in Zed via:
//   - Ctrl+Shift+B        — runs the default build task
//   - Ctrl+Shift+P → "task: spawn"  — lists all tasks
//   - Menu: Run > Task    — lists and runs tasks
//
// Available variables in the "command" and "args" fields:
//
//	$ZED_WORKTREE_ROOT  — absolute path to the project root
//	$ZED_FILE           — absolute path to the open file
//	$ZED_FILENAME       — name of the open file (without directory)
//	$ZED_COLUMN         — current cursor column
//	$ZED_ROW            — current cursor row
//
// Reference: https://zed.dev/docs/tasks
const tmplZedTasks = `[
  // ============================================================================
  // .zed/tasks.json — Tarefas de build para {{ .ProjectName }}
  // ============================================================================
  // Acesso via:
  //   Ctrl+Shift+P → "task: spawn"    lista e executa qualquer tarefa
  //   Ctrl+Shift+B                    re-executa a última tarefa usada
  //
  // Variáveis disponíveis:
  //   $ZED_WORKTREE_ROOT  raiz do projeto (onde este arquivo está)
  //   $ZED_FILE           arquivo aberto no momento
  //
  // Documentação: https://zed.dev/docs/tasks
  // ============================================================================

  // ── Configure ──────────────────────────────────────────────────────────────

  {
    "label": "CMake: Configure (Debug)",
    "command": "cmake",
    "args": [
      "--preset",
      "{{if .UseVCPKG}}vcpkg-debug{{else}}debug{{end}}"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    // Sempre exibe o painel de saída para acompanhar o progresso.
    "reveal": "always",
    // Não permite execuções simultâneas do mesmo configure.
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Configure (Release)",
    "command": "cmake",
    "args": [
      "--preset",
      "{{if .UseVCPKG}}vcpkg-release{{else}}release{{end}}"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Configure (Sanitizers)",
    "command": "cmake",
    "args": ["--preset", "sanitize"],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  // ── Build ──────────────────────────────────────────────────────────────────

  {
    "label": "CMake: Build (Debug)",
    "command": "cmake",
    "args": [
      "--build",
      "--preset",
      "{{if .UseVCPKG}}build-vcpkg-debug{{else}}build-debug{{end}}"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Build (Release)",
    "command": "cmake",
    "args": [
      "--build",
      "--preset",
      "{{if .UseVCPKG}}build-vcpkg-release{{else}}build-release{{end}}"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Build (Sanitizers)",
    "command": "cmake",
    "args": ["--build", "--preset", "build-sanitize"],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  // ── Clean ──────────────────────────────────────────────────────────────────

  {
    "label": "CMake: Clean (Debug)",
    "command": "cmake",
    "args": [
      "--build",
      "--preset",
      "{{if .UseVCPKG}}build-vcpkg-debug{{else}}build-debug{{end}}",
      "--target", "clean"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Delete build/",
    "command": "rm",
    "args": ["-rf", "build"],
    "cwd": "$ZED_WORKTREE_ROOT",
    // "no_focus" exibe a saída mas não muda o foco para o terminal.
    "reveal": "no_focus",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  // ── Testes ─────────────────────────────────────────────────────────────────

  {
    "label": "CMake: Run Tests (Debug)",
    "command": "ctest",
    "args": [
      "--preset",
      "{{if .UseVCPKG}}test-vcpkg-debug{{else}}test-debug{{end}}",
      "--output-on-failure"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Run Tests (verbose)",
    "command": "ctest",
    "args": [
      "--preset",
      "{{if .UseVCPKG}}test-vcpkg-debug{{else}}test-debug{{end}}",
      "--output-on-failure",
      "--verbose"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },
{{if .IsExecutable}}
  // ── Executar ───────────────────────────────────────────────────────────────

  {
    "label": "Run: {{ .ProjectName }} (Debug)",
    "command": "./build/{{if .UseVCPKG}}vcpkg-debug{{else}}debug{{end}}/bin/{{ .ProjectName }}",
    "args": [],
    "cwd": "$ZED_WORKTREE_ROOT",
    // "always" abre um terminal dedicado para ver a saída do programa.
    "reveal": "always",
    // Permite rodar o binário várias vezes simultaneamente se necessário.
    "allow_concurrent_runs": true,
    // Abre em um terminal separado para não misturar com saída do build.
    "use_new_terminal": true
  },

  {
    "label": "Build & Run: {{ .ProjectName }} (Debug)",
    "command": "bash",
    "args": [
      "-c",
      "cmake --build --preset {{if .UseVCPKG}}build-vcpkg-debug{{else}}build-debug{{end}} && echo '\\n─── Executando {{ .ProjectName }} ───\\n' && ./build/{{if .UseVCPKG}}vcpkg-debug{{else}}debug{{end}}/bin/{{ .ProjectName }}"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": true
  },
{{end}}
  // ── Ferramentas ─────────────────────────────────────────────────────────────

  {
    "label": "Clang-Format: Format file",
    "command": "clang-format",
    "args": ["-i", "$ZED_FILE"],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "no_focus",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "Clang-Format: Format project",
    "command": "bash",
    "args": [
      "-c",
      "find src include tests -name '*.cpp' -o -name '*.hpp' -o -name '*.h' -o -name '*.cxx' | xargs clang-format -i && echo 'Formatação concluída.'"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "always",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  },

  {
    "label": "CMake: Symlink compile_commands.json",
    "command": "bash",
    "args": [
      "-c",
      "ln -sf build/{{if .UseVCPKG}}vcpkg-debug{{else}}debug{{end}}/compile_commands.json compile_commands.json && echo 'compile_commands.json vinculado.'"
    ],
    "cwd": "$ZED_WORKTREE_ROOT",
    "reveal": "no_focus",
    "allow_concurrent_runs": false,
    "use_new_terminal": false
  }
]
`
