// Package config defines all types, constants and configuration structures
// used by cpp-gen to describe a C++ project to be generated.
package config

import "path/filepath"

// ─────────────────────────────────────────────────────────────────────────────
// FolderLayout
// ─────────────────────────────────────────────────────────────────────────────

// FolderLayout represents the folder organization pattern of the C++ project.
// Each layout defines where public headers and implementation files are placed
// and how CMake targets reference the include directories.
type FolderLayout string

const (
	// LayoutSeparate is the classic standard with separation of include/<name>/ and src/.
	// Public headers are in include/<name>/*.hpp and implementations in src/*.cpp.
	// It is the most common pattern in modern CMake projects and makes it easy to
	// distinguish the public API from the private implementation.
	//
	//  include/<name>/  ← public headers (API)
	//  src/             ← implementations (.cpp) and private headers
	//  tests/           ← tests
	LayoutSeparate FolderLayout = "separate"

	// LayoutMerged is the Pitchfork pattern (P1204R0 / vector-of-bool).
	// Headers and implementations are together in the <name>/ directory, eliminating
	// navigation between include/ and src/. Unit tests live as sibling files.
	// Canonical include: #include <<name>/file.hpp>
	//
	//  <name>/          ← headers (.hpp) and sources (.cpp) together
	//  <name>/*.test.cpp ← unit tests as sibling files (optional)
	//  tests/           ← integration/functional tests
	LayoutMerged FolderLayout = "merged"

	// LayoutFlat places everything inside src/ without separation between headers and sources.
	// It is the simplest pattern, suited for executables and small projects where
	// the distinction between public and private API is not relevant.
	//
	//  src/             ← headers (.hpp) and sources (.cpp) in the same place
	//  tests/           ← tests
	LayoutFlat FolderLayout = "flat"

	// LayoutModular follows the Pitchfork pattern for multi-module projects using libs/.
	// Each module/library lives in libs/<name>/{include,src}. Executables are placed
	// in apps/. Makes it easy to extract modules into separate projects in the future.
	//
	//  libs/<name>/include/<name>/  ← public headers
	//  libs/<name>/src/             ← implementations
	//  apps/                        ← executables (if applicable)
	//  tests/                       ← tests
	LayoutModular FolderLayout = "modular"

	// LayoutTwoRoot is a simple include/ + src/ split without a namespace subdirectory.
	// Unlike Separate, it does not create include/<name>/: headers are placed directly
	// in include/*.hpp. Common in smaller projects that do not need the namespace
	// prefix in #include.
	//
	//  include/   ← public headers (no namespace subdir)
	//  src/       ← implementations
	//  tests/     ← tests
	LayoutTwoRoot FolderLayout = "two-root"
)

// FolderLayoutOptions returns all available layouts in suggested order.
func FolderLayoutOptions() []FolderLayout {
	return []FolderLayout{
		LayoutSeparate,
		LayoutMerged,
		LayoutFlat,
		LayoutModular,
		LayoutTwoRoot,
	}
}

// Label returns the user-friendly layout name for UI display.
func (l FolderLayout) Label() string {
	switch l {
	case LayoutSeparate:
		return "Separate   — include/<nome>/ + src/"
	case LayoutMerged:
		return "Merged     — <nome>/ (Pitchfork / P1204R0)"
	case LayoutFlat:
		return "Flat       — src/ com headers e fontes juntos"
	case LayoutModular:
		return "Modular    — libs/<nome>/ (Pitchfork multi-módulo)"
	case LayoutTwoRoot:
		return "Two-Root   — include/ + src/ (sem namespace subdir)"
	default:
		return string(l)
	}
}

// Description returns a detailed explanation of the layout, displayed as a hint
// below the selection field in the TUI.
func (l FolderLayout) Description() string {
	switch l {
	case LayoutSeparate:
		return "Clássico CMake. API em include/<nome>/, impl. em src/. Mais usado em libs."
	case LayoutMerged:
		return "Pitchfork (P1204R0). Headers e .cpp juntos em <nome>/. Navegação mais fácil."
	case LayoutFlat:
		return "Tudo em src/. Ideal para executáveis e projetos simples."
	case LayoutModular:
		return "Multi-módulo. Cada lib em libs/<nome>/. Pronto para escalar."
	case LayoutTwoRoot:
		return "Include/ raiz sem namespace. Simples para bibliotecas pequenas."
	default:
		return ""
	}
}

// TreePreview returns an ASCII tree of the folder structure generated by the
// layout, using <name> as a placeholder for the project name.
// Displayed as the description of each option in the TUI layout selector.
func (l FolderLayout) TreePreview() string {
	switch l {
	case LayoutSeparate:
		return "<projeto>/\n" +
			"├─ include/\n" +
			"│   └─ <nome>/\n" +
			"│       └─ *.hpp     ← headers públicos\n" +
			"├─ src/\n" +
			"│   └─ *.cpp         ← implementações\n" +
			"└─ tests/"
	case LayoutMerged:
		return "<projeto>/\n" +
			"├─ <nome>/\n" +
			"│   ├─ *.hpp         ← headers\n" +
			"│   └─ *.cpp         ← implementações\n" +
			"└─ tests/"
	case LayoutFlat:
		return "<projeto>/\n" +
			"├─ src/\n" +
			"│   ├─ *.hpp         ← headers\n" +
			"│   └─ *.cpp         ← implementações\n" +
			"└─ tests/"
	case LayoutModular:
		return "<projeto>/\n" +
			"├─ libs/\n" +
			"│   └─ <nome>/\n" +
			"│       ├─ include/  ← headers públicos\n" +
			"│       └─ src/      ← implementações\n" +
			"├─ apps/             ← executáveis\n" +
			"└─ tests/"
	case LayoutTwoRoot:
		return "<projeto>/\n" +
			"├─ include/\n" +
			"│   └─ *.hpp         ← headers (sem namespace)\n" +
			"├─ src/\n" +
			"│   └─ *.cpp         ← implementações\n" +
			"└─ tests/"
	default:
		return ""
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Enumerated types
// ─────────────────────────────────────────────────────────────────────────────

// IDE represents the target IDE for generating specific configurations
// (tasks, launch, settings, etc.).
type IDE string

const (
	IDENone   IDE = "none"   // No IDE configuration
	IDEVSCode IDE = "vscode" // Visual Studio Code (.vscode/)
	IDECLion  IDE = "clion"  // CLion / CMakePresets.json
	IDENvim   IDE = "nvim"   // Neovim (.nvim.lua + clangd)
	IDEZed    IDE = "zed"    // Zed (.zed/settings.json + .zed/tasks.json)
)

// IDEOptions returns all available IDEs as a slice, useful for UIs.
func IDEOptions() []IDE {
	return []IDE{IDENone, IDEVSCode, IDECLion, IDENvim, IDEZed}
}

// Label returns the user-friendly IDE name for display.
func (i IDE) Label() string {
	switch i {
	case IDEVSCode:
		return "Visual Studio Code"
	case IDECLion:
		return "CLion"
	case IDENvim:
		return "Neovim"
	case IDEZed:
		return "Zed"
	default:
		return "Nenhuma"
	}
}

// ─────────────────────────────────────────────────────────────────────────────

// PackageManager represents the C++ package manager to be configured.
type PackageManager string

const (
	PkgNone         PackageManager = "none"         // No package manager
	PkgVCPKG        PackageManager = "vcpkg"        // VCPKG (vcpkg.json manifest)
	PkgFetchContent PackageManager = "fetchcontent" // CMake FetchContent
)

// PackageManagerOptions returns all available package managers.
func PackageManagerOptions() []PackageManager {
	return []PackageManager{PkgNone, PkgVCPKG, PkgFetchContent}
}

// Label returns the user-friendly package manager name for display.
func (p PackageManager) Label() string {
	switch p {
	case PkgVCPKG:
		return "VCPKG (vcpkg.json)"
	case PkgFetchContent:
		return "FetchContent (CMake nativo)"
	default:
		return "Nenhum"
	}
}

// ─────────────────────────────────────────────────────────────────────────────

// ProjectType represents the type of artifact the C++ project will generate.
type ProjectType string

const (
	TypeExecutable ProjectType = "executable"  // Executable binary
	TypeStaticLib  ProjectType = "static-lib"  // Static library (.a / .lib)
	TypeHeaderOnly ProjectType = "header-only" // Header-only library (interface)
)

// ProjectTypeOptions returns all available project types.
func ProjectTypeOptions() []ProjectType {
	return []ProjectType{TypeExecutable, TypeStaticLib, TypeHeaderOnly}
}

// Label returns the user-friendly project type name.
func (t ProjectType) Label() string {
	switch t {
	case TypeExecutable:
		return "Executável"
	case TypeStaticLib:
		return "Biblioteca Estática"
	case TypeHeaderOnly:
		return "Biblioteca Header-Only"
	default:
		return string(t)
	}
}

// IsLibrary returns true if the project is any kind of library.
func (t ProjectType) IsLibrary() bool {
	return t == TypeStaticLib || t == TypeHeaderOnly
}

// ─────────────────────────────────────────────────────────────────────────────

// CppStandard represents the ISO C++ standard version to be used.
type CppStandard string

const (
	Cpp17 CppStandard = "17" // ISO C++17
	Cpp20 CppStandard = "20" // ISO C++20
	Cpp23 CppStandard = "23" // ISO C++23
)

// CppStandardOptions returns all supported C++ standards.
func CppStandardOptions() []CppStandard {
	return []CppStandard{Cpp17, Cpp20, Cpp23}
}

// Label returns the user-friendly C++ standard name for display.
func (s CppStandard) Label() string {
	return "C++" + string(s)
}

// ─────────────────────────────────────────────────────────────────────────────

// ClangFormatStyle represents the base style for .clang-format generation.
// When set to ClangFormatLLVM, a fully customized template with modern
// overrides is generated. For all other styles, a minimal file with just
// BasedOnStyle and Standard is generated, allowing the user to build on top.
type ClangFormatStyle string

const (
	// ClangFormatLLVM generates a detailed .clang-format based on LLVM with
	// modern adjustments: 4-space indent, Allman braces, 100-col limit, etc.
	// This is the default and matches the historical behaviour of cpp-gen.
	ClangFormatLLVM ClangFormatStyle = "LLVM"

	// ClangFormatGoogle uses the Google C++ Style Guide as-is (2-space indent,
	// K&R braces, 80-col limit).
	ClangFormatGoogle ClangFormatStyle = "Google"

	// ClangFormatChromium is based on Google style, used by the Chromium project.
	ClangFormatChromium ClangFormatStyle = "Chromium"

	// ClangFormatMozilla uses the Mozilla coding style.
	ClangFormatMozilla ClangFormatStyle = "Mozilla"

	// ClangFormatWebKit uses the WebKit coding style (4-space indent, K&R braces).
	ClangFormatWebKit ClangFormatStyle = "WebKit"

	// ClangFormatMicrosoft uses the Microsoft C++ coding style.
	ClangFormatMicrosoft ClangFormatStyle = "Microsoft"

	// ClangFormatGNU uses the GNU coding standards.
	ClangFormatGNU ClangFormatStyle = "GNU"
)

// ClangFormatStyleOptions returns all available styles in suggested order.
func ClangFormatStyleOptions() []ClangFormatStyle {
	return []ClangFormatStyle{
		ClangFormatLLVM,
		ClangFormatGoogle,
		ClangFormatChromium,
		ClangFormatMozilla,
		ClangFormatWebKit,
		ClangFormatMicrosoft,
		ClangFormatGNU,
	}
}

// Label returns the user-friendly name for display in the TUI.
func (s ClangFormatStyle) Label() string {
	switch s {
	case ClangFormatLLVM:
		return "LLVM        — personalizado  (4 espaços, Allman, 100 cols)"
	case ClangFormatGoogle:
		return "Google      — Google C++ Style Guide  (2 espaços, 80 cols)"
	case ClangFormatChromium:
		return "Chromium    — baseado em Google  (Chromium project)"
	case ClangFormatMozilla:
		return "Mozilla     — Mozilla Coding Style"
	case ClangFormatWebKit:
		return "WebKit      — WebKit Coding Style  (4 espaços)"
	case ClangFormatMicrosoft:
		return "Microsoft   — Microsoft C++ Style"
	case ClangFormatGNU:
		return "GNU         — GNU Coding Standards"
	default:
		return string(s)
	}
}

// Description returns a short explanation shown as a hint in the TUI.
func (s ClangFormatStyle) Description() string {
	switch s {
	case ClangFormatLLVM:
		return "Arquivo detalhado com todas as opções documentadas. Fácil de ajustar."
	case ClangFormatGoogle:
		return "Estilo oficial do Google. Amplamente adotado em projetos open source."
	case ClangFormatChromium:
		return "Derivado do Google Style. Usado no projeto Chromium e projetos relacionados."
	case ClangFormatMozilla:
		return "Estilo oficial da Mozilla Foundation."
	case ClangFormatWebKit:
		return "Estilo usado pelo motor de layout WebKit (Safari, Qt WebEngine)."
	case ClangFormatMicrosoft:
		return "Estilo padrão de projetos Microsoft (Visual Studio)."
	case ClangFormatGNU:
		return "Padrões de codificação GNU. Comum em projetos do ecossistema GNU/Linux."
	default:
		return ""
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Main configuration structure
// ─────────────────────────────────────────────────────────────────────────────

// ProjectConfig holds all information needed to generate a complete C++ project.
// It is populated via the interactive TUI or CLI flags.
type ProjectConfig struct {
	// ── Project metadata ──────────────────────────────────────────────────────

	// Name is the project name (e.g. "my-project").
	// Used to name directories, CMake targets and variables.
	Name string

	// Description is a brief description of the project.
	Description string

	// Author is the name of the author or organization.
	Author string

	// Version is the initial project version in SemVer format (e.g. "1.0.0").
	Version string

	// ── Technical settings ────────────────────────────────────────────────────

	// Standard defines the C++ standard to be used (17, 20, 23).
	Standard CppStandard

	// ProjectType defines the artifact type: executable, library, etc.
	ProjectType ProjectType

	// Layout defines the folder and file organization pattern of the project.
	// Determines where headers and implementations are placed and how CMake references them.
	Layout FolderLayout

	// ── Tools and integrations ────────────────────────────────────────────────

	// PackageManager defines the C++ dependency management system.
	PackageManager PackageManager

	// IDE defines the target IDE for generating specific configurations.
	IDE IDE

	// ── Optional feature flags ────────────────────────────────────────────────

	// UseGit indicates whether a Git repository should be initialized in the project.
	UseGit bool

	// UseClangd indicates whether the .clangd configuration file should be generated.
	UseClangd bool

	// UseClangFormat indicates whether the .clang-format file should be generated.
	UseClangFormat bool

	// ClangFormatStyle defines the base style used for .clang-format generation.
	// When set to ClangFormatLLVM, a fully customized template is generated.
	// For all other values, a minimal BasedOnStyle file is generated.
	ClangFormatStyle ClangFormatStyle

	// ── Output configuration ──────────────────────────────────────────────────

	// OutputDir is the base directory where the project will be created.
	// The project will be at OutputDir/Name.
	OutputDir string
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper methods
// ─────────────────────────────────────────────────────────────────────────────

// ProjectPath returns the full path of the generated project root directory,
// combining OutputDir and Name in an OS-safe manner.
func (c *ProjectConfig) ProjectPath() string {
	if c.OutputDir == "" || c.OutputDir == "." {
		return c.Name
	}
	return filepath.Join(c.OutputDir, c.Name)
}

// Validate checks whether the configuration contains all required fields and
// returns a list of found errors.
func (c *ProjectConfig) Validate() []string {
	var errs []string

	if c.Name == "" {
		errs = append(errs, "nome do projeto é obrigatório")
	}
	if c.Version == "" {
		errs = append(errs, "versão do projeto é obrigatória")
	}
	if c.Standard == "" {
		errs = append(errs, "padrão C++ é obrigatório")
	}
	if c.ProjectType == "" {
		errs = append(errs, "tipo de projeto é obrigatório")
	}

	return errs
}

// Default returns a ProjectConfig with sensible default values,
// useful as a starting point before applying the user's choices.
func Default() *ProjectConfig {
	return &ProjectConfig{
		Version:          "1.0.0",
		Standard:         Cpp20,
		ProjectType:      TypeExecutable,
		Layout:           LayoutSeparate,
		PackageManager:   PkgNone,
		IDE:              IDENone,
		UseGit:           true,
		UseClangd:        true,
		UseClangFormat:   true,
		ClangFormatStyle: ClangFormatLLVM,
		OutputDir:        ".",
	}
}
