// Package localconfig implements reading and writing of the per-project
// configuration file (.cppgenrc.json) placed at the root of every C++ project
// generated by cpp-gen. It is the cpp-gen equivalent of angular.json — a
// single file that drives file generation (cpp-gen generate) by capturing
// header style, directory layout, namespace preferences and test settings.
package localconfig

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// FileName is the name of the local config file placed at the project root.
const FileName = ".cppgenrc.json"

// GlobalFileName is the name of the global config file stored under the
// user's XDG config directory (~/.config/cpp-gen/config.json).
const GlobalFileName = "config.json"

// GlobalDirName is the subdirectory inside os.UserConfigDir() used by cpp-gen.
const GlobalDirName = "cpp-gen"

// ErrNotFound is returned by Load when no .cppgenrc.json is found
// in the directory tree.
var ErrNotFound = errors.New("arquivo .cppgenrc.json não encontrado no projeto")

// ErrGlobalNotFound is returned by LoadGlobal when no global config exists.
var ErrGlobalNotFound = errors.New("configuração global não encontrada (~/.config/cpp-gen/config.json)")

// ─────────────────────────────────────────────────────────────────────────────
// Architecture configuration
// ─────────────────────────────────────────────────────────────────────────────

// ArchStyle represents the high-level architectural pattern of the project.
// It drives how cpp-gen generate resolves file paths and which schematics
// are available by default.
type ArchStyle string

const (
	ArchFlat      ArchStyle = "flat"      // No layer organization; all files in src/include
	ArchLayered   ArchStyle = "layered"   // Clean Architecture: domain/application/infrastructure/presentation
	ArchModular   ArchStyle = "modular"   // Feature modules: modules/<feature>/
	ArchHexagonal ArchStyle = "hexagonal" // Ports & Adapters: core/ports + adapters/
	ArchMVC       ArchStyle = "mvc"       // Model-View-Controller: models/ views/ controllers/
	ArchMVVM      ArchStyle = "mvvm"      // Model-View-ViewModel: models/ viewmodels/ views/
	ArchECS       ArchStyle = "ecs"       // Entity-Component-System: systems/ components/ core/
)

// ArchPlacement controls how generated files are distributed within the
// source tree when an architecture style is active.
type ArchPlacement string

const (
	// PlacementByLayer groups files under their architectural layer directory.
	// Example: src/application/user/user_service.hpp
	PlacementByLayer ArchPlacement = "by-layer"

	// PlacementByFeature groups all files for a feature together.
	// Example: src/user/user_service.hpp
	PlacementByFeature ArchPlacement = "by-feature"

	// PlacementByType groups files by their kind (services/, repositories/, etc.).
	// Example: src/services/user_service.hpp
	PlacementByType ArchPlacement = "by-type"
)

// ArchitectureConfig describes the architectural conventions of the project.
// It is written to .cppgenrc.json during cpp-gen new and read by
// cpp-gen generate to resolve file paths and available schematics.
type ArchitectureConfig struct {
	// Style is the high-level architectural pattern.
	Style ArchStyle `json:"style"`

	// Layers lists the architectural layers present in the project.
	// Only meaningful for layered and hexagonal styles.
	// Examples: ["domain","application","infrastructure","presentation"]
	Layers []string `json:"layers,omitempty"`

	// Patterns lists the design patterns the project adopts.
	// These are used to determine which built-in schematics are pre-configured.
	// Examples: ["repository","service","command","observer"]
	Patterns []string `json:"patterns,omitempty"`

	// Placement controls how generate resolves output directories.
	Placement ArchPlacement `json:"placement"`

	// HeaderOnly indicates that .hpp and .cpp files are kept in the same
	// directory (no separate include/ tree). Set to true when the project
	// was created with a merged or flat folder layout.
	HeaderOnly bool `json:"header_only"`

	// DefaultLayer is the layer used when --layer is not supplied to
	// cpp-gen generate. Only relevant for layered/hexagonal styles.
	DefaultLayer string `json:"default_layer,omitempty"`
}

// ─────────────────────────────────────────────────────────────────────────────
// Custom schematics
// ─────────────────────────────────────────────────────────────────────────────

// CustomSchematicFile describes one file within a custom schematic.
// The Path field is a Go text/template string evaluated with SchematicTemplateData.
type CustomSchematicFile struct {
	// Role is a short semantic label for this file within the schematic.
	// Examples: "interface", "impl", "impl_header", "test", "types"
	Role string `json:"role"`

	// Path is a Go template for the output path relative to the project root.
	// Available variables: .NameSnake, .NamePascal, .NameUpper, .Layer,
	//                      .Namespace, .ProjectName, .Src, .Include, .Tests
	Path string `json:"path"`

	// Template names the built-in file template to use for rendering content.
	// Values: "class_hpp" | "class_cpp" | "struct_hpp" | "interface_hpp" |
	//         "free_hpp"  | "free_cpp"  | "test"
	Template string `json:"template"`

	// Brief is an optional fixed description for the @brief header field of
	// this specific file. If empty, the schematic-level brief is used.
	Brief string `json:"brief,omitempty"`
}

// CustomSchematic defines a user-provided schematic stored in .cppgenrc.json.
// Custom schematics override built-ins with the same name.
type CustomSchematic struct {
	// Description is shown in cpp-gen generate --list.
	Description string `json:"description"`

	// Files is the ordered list of files this schematic produces.
	Files []CustomSchematicFile `json:"files"`
}

// LocalConfig holds the per-project configuration read from .cppgenrc.json.
// It drives file generation (cpp-gen generate) by defining header style,
// directory paths, namespace and test preferences.
type LocalConfig struct {
	ProjectName  string                     `json:"project_name"`
	Author       string                     `json:"author"`
	Organization string                     `json:"organization,omitempty"`
	License      string                     `json:"license,omitempty"` // MIT | Apache-2.0 | GPL-3.0 | none
	Header       HeaderConfig               `json:"header"`
	Paths        PathsConfig                `json:"paths"`
	Namespace    NamespaceConfig            `json:"namespace"`
	Generate     GenerateConfig             `json:"generate"`
	Architecture ArchitectureConfig         `json:"architecture"`
	Schematics   map[string]CustomSchematic `json:"schematics,omitempty"`
}

// HeaderConfig controls whether and how a file header comment is generated
// at the top of every .cpp / .hpp file produced by cpp-gen.
type HeaderConfig struct {
	Enabled    bool     `json:"enabled"`
	Style      string   `json:"style"`       // doxygen | block | line | none
	Fields     []string `json:"fields"`      // file, brief, author, date, version, copyright, license
	DateFormat string   `json:"date_format"` // Go time layout, e.g. "2006-01-02"
}

// PathsConfig holds the project-relative directories where cpp-gen places
// generated source files, headers and test files.
type PathsConfig struct {
	Src     string `json:"src"`
	Include string `json:"include"`
	Tests   string `json:"tests"`
}

// NamespaceConfig determines whether generated code is wrapped in a C++
// namespace and, if so, which name to use.
type NamespaceConfig struct {
	Enabled bool   `json:"enabled"`
	Name    string `json:"name"`
}

// GenerateConfig captures defaults that apply whenever cpp-gen generate is
// invoked without explicit flags.
type GenerateConfig struct {
	DefaultType   string `json:"default_type"`   // class | struct | free | interface
	TestFramework string `json:"test_framework"` // catch2 | gtest | none
	CreateTest    bool   `json:"create_test"`
}

// DefaultLocalConfig returns a *LocalConfig populated with sensible defaults
// for a new project. The caller supplies the project name (used as the default
// namespace) and the author string.
func DefaultLocalConfig(projectName, author string) *LocalConfig {
	return &LocalConfig{
		ProjectName: projectName,
		Author:      author,
		Header: HeaderConfig{
			Enabled:    true,
			Style:      "doxygen",
			Fields:     []string{"file", "brief", "author", "date"},
			DateFormat: "2006-01-02",
		},
		Paths: PathsConfig{
			Src:     "src",
			Include: "include",
			Tests:   "tests",
		},
		Namespace: NamespaceConfig{
			Enabled: true,
			Name:    projectName,
		},
		Architecture: DefaultArchitecture(ArchFlat),
		Generate: GenerateConfig{
			DefaultType:   "class",
			TestFramework: "catch2",
			CreateTest:    true,
		},
	}
}

// DefaultArchitecture returns a pre-filled ArchitectureConfig for the given style.
// It sets sensible defaults for layers, patterns, placement and default layer.
func DefaultArchitecture(style ArchStyle) ArchitectureConfig {
	switch style {
	case ArchLayered:
		return ArchitectureConfig{
			Style:        ArchLayered,
			Layers:       []string{"domain", "application", "infrastructure", "presentation"},
			Patterns:     []string{"repository", "service"},
			Placement:    PlacementByLayer,
			DefaultLayer: "application",
		}
	case ArchModular:
		return ArchitectureConfig{
			Style:     ArchModular,
			Layers:    []string{},
			Patterns:  []string{"service", "repository"},
			Placement: PlacementByFeature,
		}
	case ArchHexagonal:
		return ArchitectureConfig{
			Style:        ArchHexagonal,
			Layers:       []string{"core", "adapters"},
			Patterns:     []string{"repository", "service", "factory"},
			Placement:    PlacementByLayer,
			DefaultLayer: "core",
		}
	case ArchMVC:
		return ArchitectureConfig{
			Style:        ArchMVC,
			Layers:       []string{"models", "views", "controllers"},
			Patterns:     []string{"controller", "model"},
			Placement:    PlacementByType,
			DefaultLayer: "controllers",
		}
	case ArchMVVM:
		return ArchitectureConfig{
			Style:        ArchMVVM,
			Layers:       []string{"models", "viewmodels", "views"},
			Patterns:     []string{"model", "viewmodel"},
			Placement:    PlacementByType,
			DefaultLayer: "viewmodels",
		}
	case ArchECS:
		return ArchitectureConfig{
			Style:        ArchECS,
			Layers:       []string{"systems", "components", "core"},
			Patterns:     []string{"system", "component", "subsystem", "event"},
			Placement:    PlacementByType,
			DefaultLayer: "systems",
		}
	default: // ArchFlat
		return ArchitectureConfig{
			Style:     ArchFlat,
			Patterns:  []string{},
			Placement: PlacementByType,
		}
	}
}

// Load searches for a .cppgenrc.json file starting from dir and walking up
// the directory tree. It stops after at most 10 levels. If no file is found,
// ErrNotFound is returned.
func Load(dir string) (*LocalConfig, error) {
	current := dir
	for range 10 {
		candidate := filepath.Join(current, FileName)
		data, err := os.ReadFile(candidate)
		if err == nil {
			var cfg LocalConfig
			if jsonErr := json.Unmarshal(data, &cfg); jsonErr != nil {
				return nil, jsonErr
			}
			return &cfg, nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return nil, err
		}

		parent := filepath.Dir(current)
		if parent == current {
			// Reached the filesystem root.
			break
		}
		current = parent
	}
	return nil, ErrNotFound
}

// Write serialises cfg as indented JSON and writes it to FileName inside dir,
// creating or overwriting the file with permission 0644.
func Write(dir string, cfg *LocalConfig) error {
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, FileName), data, 0644)
}

// Exists reports whether a .cppgenrc.json file is present directly in dir.
// It does not walk parent directories.
func Exists(dir string) bool {
	_, err := os.Stat(filepath.Join(dir, FileName))
	return err == nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Global config (~/.config/cpp-gen/config.json)
// ─────────────────────────────────────────────────────────────────────────────

// GlobalConfigDir returns the directory where the global cpp-gen config is
// stored. It follows the XDG Base Directory convention via os.UserConfigDir(),
// which resolves to:
//   - Linux/macOS: ~/.config/cpp-gen
//   - Windows:     %AppData%\cpp-gen
func GlobalConfigDir() (string, error) {
	base, err := os.UserConfigDir()
	if err != nil {
		return "", fmt.Errorf("não foi possível determinar o diretório de config do usuário: %w", err)
	}
	return filepath.Join(base, GlobalDirName), nil
}

// LoadGlobal reads the global configuration file. Returns ErrGlobalNotFound
// if the file does not exist yet.
func LoadGlobal() (*LocalConfig, error) {
	dir, err := GlobalConfigDir()
	if err != nil {
		return nil, err
	}

	data, err := os.ReadFile(filepath.Join(dir, GlobalFileName))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, ErrGlobalNotFound
		}
		return nil, err
	}

	var cfg LocalConfig
	if err := json.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("erro ao decodificar config global: %w", err)
	}
	return &cfg, nil
}

// WriteGlobal serialises cfg and writes it to the global config file,
// creating the ~/.config/cpp-gen directory if necessary.
func WriteGlobal(cfg *LocalConfig) error {
	dir, err := GlobalConfigDir()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("erro ao criar diretório de config global: %w", err)
	}

	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, GlobalFileName), data, 0644)
}

// GlobalExists reports whether the global config file is present.
func GlobalExists() bool {
	dir, err := GlobalConfigDir()
	if err != nil {
		return false
	}
	_, err = os.Stat(filepath.Join(dir, GlobalFileName))
	return err == nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Config resolution (local → global → built-in default)
// ─────────────────────────────────────────────────────────────────────────────

// ResolveSource indicates which config source was used by Resolve.
type ResolveSource int

const (
	// SourceLocal means a .cppgenrc.json was found in the project tree.
	SourceLocal ResolveSource = iota
	// SourceGlobal means the global ~/.config/cpp-gen/config.json was used.
	SourceGlobal
	// SourceDefault means neither local nor global config was found and the
	// built-in defaults were returned.
	SourceDefault
)

// String returns a human-readable label for the source.
func (s ResolveSource) String() string {
	switch s {
	case SourceLocal:
		return "local (.cppgenrc.json)"
	case SourceGlobal:
		return "global (~/.config/cpp-gen/config.json)"
	default:
		return "padrão embutido"
	}
}

// Resolve returns the effective LocalConfig for the project rooted at dir.
// Priority order:
//  1. Local — .cppgenrc.json found anywhere in the directory tree above dir.
//  2. Global — ~/.config/cpp-gen/config.json.
//  3. Default — built-in defaults (project name inferred from dir basename).
//
// The second return value indicates which source was used.
func Resolve(dir string) (*LocalConfig, ResolveSource, error) {
	// 1. Try local config.
	if cfg, err := Load(dir); err == nil {
		return cfg, SourceLocal, nil
	} else if !errors.Is(err, ErrNotFound) {
		return nil, SourceDefault, err
	}

	// 2. Try global config.
	if cfg, err := LoadGlobal(); err == nil {
		return cfg, SourceGlobal, nil
	} else if !errors.Is(err, ErrGlobalNotFound) {
		return nil, SourceDefault, err
	}

	// 3. Fall back to built-in defaults.
	return DefaultLocalConfig(filepath.Base(dir), ""), SourceDefault, nil
}
