// Package generator contém toda a lógica de geração de projetos C++ do cpp-gen.
package generator

import (
	"fmt"
	"os/exec"
	"path/filepath"
)

// ─────────────────────────────────────────────────────────────────────────────
// generateGit — ponto de entrada
// ─────────────────────────────────────────────────────────────────────────────

// generateGit coordena todas as operações relacionadas ao repositório Git:
//
//  1. Gera o README.md (sempre, independente de UseGit)
//  2. Gera o .gitignore (sempre, independente de UseGit)
//  3. Executa `git init` e cria um commit inicial (somente se UseGit == true)
//
// A separação entre geração dos arquivos e inicialização do git permite que
// projetos sem git ainda tenham um .gitignore e README prontos para uso futuro.
func generateGit(root string, data *TemplateData, verbose bool) error {
	// ── README.md ─────────────────────────────────────────────────────────────
	readmePath := filepath.Join(root, "README.md")
	if err := writeTemplate(readmePath, "readme", tmplReadme, data, verbose); err != nil {
		return fmt.Errorf("gerar README.md: %w", err)
	}

	// ── .gitignore ────────────────────────────────────────────────────────────
	gitignorePath := filepath.Join(root, ".gitignore")
	if err := writeTemplate(gitignorePath, "gitignore", tmplGitignore, data, verbose); err != nil {
		return fmt.Errorf("gerar .gitignore: %w", err)
	}

	// ── Git init + commit inicial ─────────────────────────────────────────────
	if data.UseGit {
		if err := initGitRepository(root, data, verbose); err != nil {
			// Falha no git não é crítica — o projeto foi gerado corretamente.
			// Apenas avisa o usuário em vez de abortar toda a geração.
			fmt.Printf("    ⚠ Aviso: não foi possível inicializar o Git: %v\n", err)
			fmt.Printf("      Execute manualmente: cd %s && git init\n", root)
		}
	}

	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// initGitRepository
// ─────────────────────────────────────────────────────────────────────────────

// initGitRepository executa a sequência de comandos Git para inicializar
// um repositório limpo com um commit inicial contendo todos os arquivos gerados.
//
// Sequência executada:
//  1. git init
//  2. git add .
//  3. git commit -m "chore: initial project setup via cpp-gen"
//
// Se o binário `git` não estiver disponível no PATH, retorna um erro descritivo.
func initGitRepository(root string, data *TemplateData, verbose bool) error {
	// Verifica se o git está disponível antes de tentar executar qualquer comando.
	if _, err := exec.LookPath("git"); err != nil {
		return fmt.Errorf("binário 'git' não encontrado no PATH; instale o Git e execute manualmente")
	}

	// ── git init ──────────────────────────────────────────────────────────────
	if err := runGitCommand(root, verbose, "init", "-b", "main"); err != nil {
		// Algumas versões antigas do git não suportam -b; tenta sem a flag.
		if err2 := runGitCommand(root, verbose, "init"); err2 != nil {
			return fmt.Errorf("git init: %w", err2)
		}
	}

	// ── git add . ─────────────────────────────────────────────────────────────
	if err := runGitCommand(root, verbose, "add", "."); err != nil {
		return fmt.Errorf("git add: %w", err)
	}

	// ── git commit ────────────────────────────────────────────────────────────
	commitMsg := fmt.Sprintf(
		"chore: initial project setup\n\nProject '%s' v%s generated by cpp-gen.\n\n- CMake %s with C++%s standard\n- Package manager: %s\n- IDE: %s",
		data.Name,
		data.Version,
		"3.20+",
		data.Standard,
		packageManagerLabel(data),
		ideLabel(data),
	)

	if err := runGitCommand(root, verbose, "commit", "-m", commitMsg); err != nil {
		return fmt.Errorf("git commit: %w", err)
	}

	if verbose {
		fmt.Printf("    ✓ Repositório Git inicializado em %s\n", root)
	}

	return nil
}

// runGitCommand executa um comando git no diretório root e retorna qualquer erro.
// Se verbose for true, imprime a saída completa do comando no stdout.
func runGitCommand(root string, verbose bool, args ...string) error {
	cmd := exec.Command("git", args...)
	cmd.Dir = root

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %v: %w\n%s", args, err, string(output))
	}

	if verbose && len(output) > 0 {
		fmt.Printf("    git %v\n    %s\n", args, string(output))
	}

	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers de label
// ─────────────────────────────────────────────────────────────────────────────

// packageManagerLabel retorna uma string descritiva do gerenciador de pacotes
// para uso na mensagem de commit inicial.
func packageManagerLabel(data *TemplateData) string {
	switch {
	case data.UseVCPKG:
		return "vcpkg"
	case data.UseFetchContent:
		return "FetchContent"
	default:
		return "none"
	}
}

// ideLabel retorna uma string descritiva da IDE configurada
// para uso na mensagem de commit inicial.
func ideLabel(data *TemplateData) string {
	switch {
	case data.IsVSCode:
		return "VSCode"
	case data.IsCLion:
		return "CLion"
	case data.IsNvim:
		return "Neovim"
	default:
		return "none"
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Template: .gitignore
// ─────────────────────────────────────────────────────────────────────────────

// tmplGitignore é o template para o arquivo .gitignore do projeto C++.
//
// Cobre os padrões mais comuns de:
//   - Artefatos de build CMake
//   - IDEs (VSCode, CLion, Vim/Neovim, Visual Studio, Xcode)
//   - Sistemas operacionais (macOS, Windows, Linux)
//   - Ferramentas de análise (coverage, sanitizers, profilers)
const tmplGitignore = `# =============================================================================
# .gitignore para projetos C++ com CMake
# Gerado pelo cpp-gen (https://github.com/cpp-gen/cpp-gen)
# =============================================================================

# ── Diretórios de build CMake ─────────────────────────────────────────────────
build/
build-*/
out/
install/
_build/

# Arquivos gerados pelo CMake
CMakeCache.txt
CMakeFiles/
cmake_install.cmake
CTestTestfile.cmake
CPackConfig.cmake
CPackSourceConfig.cmake
_CPack_Packages/
compile_commands.json

# Presets de usuário (configurações locais, não devem ser versionadas)
CMakeUserPresets.json

# ── VCPKG ─────────────────────────────────────────────────────────────────────
vcpkg_installed/
.vcpkg-clangd/

# ── Artefatos de compilação ───────────────────────────────────────────────────
*.o
*.obj
*.a
*.lib
*.so
*.so.*
*.dylib
*.dll
*.exe
*.out
*.app
*.dSYM/

# Binários gerados (na raiz do projeto — prefer usar build/)
{{.Name}}
{{.Name}}.exe

# ── Cobertura de código ───────────────────────────────────────────────────────
*.gcov
*.gcda
*.gcno
coverage/
coverage.info
lcov.info
html_coverage/

# ── Sanitizers e profiling ────────────────────────────────────────────────────
*.asan
*.tsan
*.msan
*.ubsan
callgrind.out.*
massif.out.*
perf.data
perf.data.old

# ── IDEs — VSCode ─────────────────────────────────────────────────────────────
# Mantém .vscode/ versionado (tasks, launch, settings fazem parte do projeto),
# mas ignora configurações pessoais do usuário.
.vscode/*.log
.vscode/ipch/
.vscode/.browse.VC.db*

# ── IDEs — CLion / JetBrains ─────────────────────────────────────────────────
.idea/
*.iml
cmake-build-*/

# ── IDEs — Vim / Neovim ───────────────────────────────────────────────────────
*.swp
*.swo
*~
.netrwhist
Session.vim
.session.vim

# ── IDEs — Visual Studio ──────────────────────────────────────────────────────
.vs/
*.sln
*.vcxproj
*.vcxproj.filters
*.vcxproj.user
*.suo
*.user
*.userosscache
*.sln.docstates
ipch/
x64/
x86/
[Dd]ebug/
[Rr]elease/
[Rr]eleases/
x64/
x86/

# ── IDEs — Xcode ─────────────────────────────────────────────────────────────
*.xcodeproj/
*.xcworkspace/
xcuserdata/
*.moved-aside
*.pbxuser
*.perspectivev3
*.mode1v3
*.mode2v3

# ── Sistema Operacional — macOS ───────────────────────────────────────────────
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
.AppleDouble
.LSOverride
Icon?

# ── Sistema Operacional — Windows ─────────────────────────────────────────────
Thumbs.db
Thumbs.db:encryptable
ehthumbs.db
ehthumbs_vista.db
desktop.ini
$RECYCLE.BIN/
*.lnk

# ── Sistema Operacional — Linux ───────────────────────────────────────────────
.fuse_hidden*
.directory
.Trash-*
.nfs*

# ── Logs e temporários ────────────────────────────────────────────────────────
*.log
*.tmp
*.temp
*.bak
*.orig
*.rej

# ── Documentação gerada ───────────────────────────────────────────────────────
docs/html/
docs/latex/
docs/xml/
Doxyfile.bak

# ── Dependências locais (não gerenciadas pelo VCS) ────────────────────────────
third_party/
vendor/
extern/
`

// ─────────────────────────────────────────────────────────────────────────────
// Template: README.md
// ─────────────────────────────────────────────────────────────────────────────

// tmplReadme é o template para o README.md inicial do projeto.
//
// O README inclui:
//   - Badges de status (placeholders para CI e versão)
//   - Descrição e features do projeto
//   - Requisitos de build
//   - Instruções de build com CMake Presets
//   - Estrutura de pastas
//   - Instruções de contribuição e licença
const tmplReadme = `# {{.Name}}

{{if .Description}}> {{.Description}}{{else}}> Projeto C++ moderno gerado pelo [cpp-gen](https://github.com/cpp-gen/cpp-gen).{{end}}

![Build Status](https://img.shields.io/badge/build-passing-brightgreen)
![C++ Standard](https://img.shields.io/badge/C%2B%2B-{{.Standard}}-blue)
![CMake](https://img.shields.io/badge/CMake-3.20%2B-blue)
![License](https://img.shields.io/badge/license-MIT-green)

---

## Sumário

- [Sobre](#sobre)
- [Requisitos](#requisitos)
- [Build](#build)
- [Testes](#testes)
- [Estrutura do Projeto](#estrutura-do-projeto)
- [Contribuindo](#contribuindo)
- [Licença](#licença)

---

## Sobre

{{if .Description}}{{.Description}}{{else}}Descreva aqui o propósito e as funcionalidades principais do projeto.{{end}}

{{if .Author}}**Autor:** {{.Author}}  {{end}}
**Versão:** {{.Version}}
**Padrão C++:** C++{{.Standard}}

---

## Requisitos

| Ferramenta | Versão Mínima | Observação |
|------------|:-------------:|------------|
| CMake      | 3.20          | Necessário para CMakePresets.json |
| GCC        | 11+           | Alternativa: Clang 14+ ou MSVC 19.29+ |
| Clang      | 14+           | Recomendado com Clangd |
| Ninja      | 1.10+         | Gerador padrão dos presets |
{{- if .UseVCPKG}}
| VCPKG      | recente       | Defina ` + "`" + `VCPKG_ROOT` + "`" + ` no ambiente |
{{- end}}

### Instalação das dependências (Ubuntu / Debian)

` + "```" + `bash
sudo apt update
sudo apt install -y cmake ninja-build gcc g++ clang
` + "```" + `

### Instalação das dependências (macOS)

` + "```" + `bash
brew install cmake ninja llvm
` + "```" + `
{{- if .UseVCPKG}}

### Configuração do VCPKG

` + "```" + `bash
# Clone e bootstrap do VCPKG
git clone https://github.com/microsoft/vcpkg.git ~/vcpkg
~/vcpkg/bootstrap-vcpkg.sh        # Linux / macOS
# ~/vcpkg/bootstrap-vcpkg.bat     # Windows

# Adicione ao seu shell profile (~/.bashrc, ~/.zshrc, etc.)
export VCPKG_ROOT="$HOME/vcpkg"
export PATH="$VCPKG_ROOT:$PATH"
` + "```" + `
{{- end}}

---

## Build

Este projeto usa **CMakePresets.json** para gerenciar as configurações de build.
Todos os presets são compatíveis com VSCode CMake Tools, CLion e a CLI do CMake.

### Listar presets disponíveis

` + "```" + `bash
cmake --list-presets
` + "```" + `

### Build de desenvolvimento (Debug)

` + "```" + `bash
{{- if .UseVCPKG}}
# Com VCPKG (requer VCPKG_ROOT definido)
cmake --preset vcpkg-debug
cmake --build --preset build-vcpkg-debug
{{- else}}
cmake --preset debug
cmake --build --preset build-debug
{{- end}}
` + "```" + `

### Build de produção (Release)

` + "```" + `bash
{{- if .UseVCPKG}}
cmake --preset vcpkg-release
cmake --build --preset build-vcpkg-release
{{- else}}
cmake --preset release
cmake --build --preset build-release
{{- end}}
` + "```" + `
{{- if .IsExecutable}}

### Executar

` + "```" + `bash
{{- if .UseVCPKG}}
./build/vcpkg-debug/bin/{{.Name}}
{{- else}}
./build/debug/bin/{{.Name}}
{{- end}}
` + "```" + `
{{- end}}

### Build sem presets (modo manual)

` + "```" + `bash
cmake -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build
` + "```" + `

---

## Testes

Os testes são registrados com **CTest** e podem ser executados com:

` + "```" + `bash
# Após o build de debug
{{- if .UseVCPKG}}
ctest --preset test-vcpkg-debug
{{- else}}
ctest --preset test-debug
{{- end}}

# Ou manualmente
cd build/debug
ctest --output-on-failure
` + "```" + `

---

## Estrutura do Projeto

` + "```" + `
{{.Name}}/
├── CMakeLists.txt          # Configuração principal do CMake
├── CMakePresets.json       # Presets de configure, build e test
├── README.md               # Este arquivo
{{- if .UseGit}}
├── .gitignore              # Padrões de arquivos ignorados pelo Git
{{- end}}
{{- if .UseClangd}}
├── .clangd                 # Configuração do servidor LSP Clangd
{{- end}}
{{- if .UseClangFormat}}
├── .clang-format           # Regras de formatação de código
{{- end}}
├── cmake/
│   ├── CompilerWarnings.cmake  # Flags de warning para GCC/Clang/MSVC
{{- if .UseVCPKG}}
│   └── (vcpkg via toolchain)   # Integração VCPKG via CMakePresets.json
{{- end}}
{{- if .UseFetchContent}}
│   └── Dependencies.cmake      # Dependências via FetchContent
{{- end}}
{{- if not .IsHeaderOnly}}
├── src/
│   ├── CMakeLists.txt      # Target principal
{{- if .IsExecutable}}
│   └── main.cpp            # Ponto de entrada
{{- else}}
│   └── {{.NameSnake}}.cpp  # Implementação da biblioteca
{{- end}}
{{- end}}
├── include/
│   └── {{.Name}}/
{{- if .IsExecutable}}
│       └── (headers públicos)
{{- else}}
│       └── {{.NameSnake}}.hpp  # API pública
{{- end}}
├── tests/
│   ├── CMakeLists.txt      # Targets de teste
│   └── test_main.cpp       # Testes unitários
└── docs/                   # Documentação (Doxygen, Markdown, etc.)
` + "```" + `

---

## Contribuindo

1. Faça um fork do repositório
2. Crie uma branch para sua feature: ` + "`" + `git checkout -b feature/minha-feature` + "`" + `
3. Commit suas mudanças: ` + "`" + `git commit -m 'feat: adiciona minha feature'` + "`" + `
4. Push para a branch: ` + "`" + `git push origin feature/minha-feature` + "`" + `
5. Abra um Pull Request

### Convenção de commits

Este projeto segue o padrão [Conventional Commits](https://www.conventionalcommits.org/):

- ` + "`" + `feat:` + "`" + ` — nova funcionalidade
- ` + "`" + `fix:` + "`" + ` — correção de bug
- ` + "`" + `docs:` + "`" + ` — documentação
- ` + "`" + `refactor:` + "`" + ` — refatoração sem mudança de comportamento
- ` + "`" + `test:` + "`" + ` — adição ou correção de testes
- ` + "`" + `chore:` + "`" + ` — tarefas de manutenção (build, CI, deps)

---

## Licença

Copyright © {{.Year}}{{if .Author}} {{.Author}}{{end}}. Todos os direitos reservados.

> Substitua esta seção pela licença do seu projeto.
> Exemplos: [MIT](https://opensource.org/licenses/MIT), [Apache 2.0](https://opensource.org/licenses/Apache-2.0), [GPL-3.0](https://opensource.org/licenses/GPL-3.0).

---

*Gerado com ❤️ por [cpp-gen](https://github.com/cpp-gen/cpp-gen) em {{.Year}}.*
`
